[package]
name = "shader_playground"
version = "0.1.0"
edition = "2018"

[dependencies]
wgpu = "0.8"
winit = "0.24"
imgui = "0.7"
imgui-wgpu = "0.15"
imgui-winit-support = "0.7"

shaderc = "0.7"
spirv-reflect = "0.2"

notify = "4"
pollster = "0.2.4"

log = "0.4"
env_logger = "0.8"